project:
  name: "ucuenca-sabe"
  version: "1.0.0"

paths:
  # Capas base
  data_root: "data"
  bronze: "data/bronze"
  silver: "data/silver"
  gold: "data/gold"
  
  # Directorios específicos de fuentes de datos (Se crearán automáticamente)
  enemdu_bronze: "data/bronze/externas/enemdu"
  internas_bronze: "data/bronze/internas"
  investigacion_bronze: "data/bronze/investigacion"
  gold_empleabilidad: "data/gold/eje_empleabilidad"

enemdu:
  kaggle_dataset: "kmichelle/enemdu-ecuador-microdatos-anuales-personas"