table autoridades_admin
	lineageTag: c454c6c6-0789-46c9-864e-1a83e0c3bf60

	column N°
		dataType: int64
		formatString: 0
		lineageTag: ee1226bd-02e5-42fe-ae99-644b38d69071
		summarizeBy: sum
		sourceColumn: N°

		annotation SummarizationSetBy = Automatic

	column NOMBRES
		dataType: string
		lineageTag: 8f92351d-c435-4996-8f00-7f9d3b38211f
		summarizeBy: none
		sourceColumn: NOMBRES

		annotation SummarizationSetBy = Automatic

	column 'DENOMINACION DEL CARGO'
		dataType: string
		lineageTag: b059c784-3b7d-40c8-9212-568e03591a97
		summarizeBy: none
		sourceColumn: DENOMINACION DEL CARGO

		annotation SummarizationSetBy = Automatic

	column 'CORREO ELECTRONICO'
		dataType: string
		lineageTag: 56309c83-6264-4fc8-81d8-75e1a23b0dab
		summarizeBy: none
		sourceColumn: CORREO ELECTRONICO

		annotation SummarizationSetBy = Automatic

	column CARRERA
		dataType: string
		lineageTag: 92cb4e74-5f50-4407-aa75-15237894ecff
		summarizeBy: none
		sourceColumn: CARRERA

		annotation SummarizationSetBy = Automatic

	column 'FACULTAD / INSTITUTO'
		dataType: string
		lineageTag: a219fc20-f205-48a8-a896-beaf7baaeb43
		summarizeBy: none
		sourceColumn: FACULTAD / INSTITUTO

		annotation SummarizationSetBy = Automatic

	column Key_nombre
		dataType: string
		lineageTag: cf86ae09-eae7-4237-8480-4c517c181f06
		summarizeBy: none
		sourceColumn: Key_nombre

		annotation SummarizationSetBy = Automatic

	column FACULTAD_KEY
		dataType: string
		lineageTag: e02121e4-947e-4dc6-bebe-8dd8c1258153
		summarizeBy: none
		sourceColumn: FACULTAD_KEY

		annotation SummarizationSetBy = Automatic

	column ANTIGUEDAD =
			
			LOOKUPVALUE(
			    catastro_docentes[Antiguedad],
			    catastro_docentes[investigador],
			    autoridades_admin[Key_nombre]
			)
		formatString: 0
		lineageTag: fa9d1ef0-83ea-4e58-bfbe-378550125fad
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'TIPO TITULO' =
			
			LOOKUPVALUE(
			    catastro_docentes[TIPO TÍTULO],
			    catastro_docentes[Key_investigador],
			    autoridades_admin[Key_nombre]
			)
		lineageTag: d46af8ea-f2b8-4ebb-8525-e83bafe0e6a1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'NIVEL TITULO' =
			
			LOOKUPVALUE(
			    catastro_docentes[NIVEL TÍTULO],
			    catastro_docentes[Key_investigador],
			    autoridades_admin[Key_nombre]
			)
		lineageTag: 49cb727c-5576-4313-85dd-a5338c79c463
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'NOMBRE TITULO' =
			
			LOOKUPVALUE(
			    catastro_docentes[NOMBRE TÍTULO],
			    catastro_docentes[Key_investigador],
			    autoridades_admin[Key_nombre]
			)
		lineageTag: db6ef9c8-b5dc-41ec-83b9-3c9316c8805d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition autoridades_admin = m
		mode: import
		source =
				let
				  Origen = Excel.Workbook(File.Contents("C:\Users\michu\mis-proyectos\ucuenca-sabe\data\bronze\internas\autoridades_admin.xlsx"), null, true),
				  #"Navegación 1" = Origen{[Item = "Hoja1", Kind = "Sheet"]}[Data],
				  #"Encabezados promovidos" = Table.PromoteHeaders(#"Navegación 1", [PromoteAllScalars = true]),
				  #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"N°", Int64.Type}, {"NOMBRES", type text}, {"DENOMINACION DEL CARGO", type text}, {"CORREO ELECTRONICO", type text}, {"CARRERA", type text}, {"FACULTAD / INSTITUTO", type text}}, "es"),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo de columna cambiado",{"Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13"}),
				    #"Personalizada agregada" = Table.AddColumn(#"Columnas quitadas", "Key_nombre", each Text.Upper(
				    Text.Replace(
				        Text.Replace(
				            Text.Replace(
				                Text.Replace(
				                    Text.Replace(
				                        Text.Replace(
				                            Text.Replace(
				                                Text.Replace(
				                                    Text.Replace(
				                                        Text.Trim(Text.Clean([NOMBRES])),
				                                        "Á", "A"
				                                    ),
				                                    "É", "E"
				                                ),
				                                "Í", "I"
				                            ),
				                            "Ó", "O"
				                        ),
				                        "Ú", "U"
				                    ),
				                    "Ü", "U"
				                ),
				                "Ñ", "N"
				            ),
				            ",", ""
				        ),
				        "  ", " "
				    )
				)),
				    #"Filas filtradas4" = Table.SelectRows(#"Personalizada agregada", each true),
				    #"Filas filtradas" = Table.SelectRows(#"Filas filtradas4", each ([Key_nombre] <> null)),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Filas filtradas","FACULTAD JURISPRUDENCIA Y CIENCIAS POLITICAS Y SOCIALES","FACULTAD DE JURISPRUDENCIA Y CIENCIAS POLITICAS Y SOCIALES",Replacer.ReplaceText,{"FACULTAD / INSTITUTO"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado",null,"FACULTAD DE CIENCIAS DE LA HOSPITALIDAD",Replacer.ReplaceValue,{"FACULTAD / INSTITUTO"}),
				    #"Filas filtradas1" = Table.SelectRows(#"Valor reemplazado1", each true),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Filas filtradas1","FACULTAD JURISPRUDENCIA Y CIENCIAS POLITICAS Y SOCIALES","FACULTAD DE JURISPRUDENCIA Y CIENCIAS POLITICAS Y SOCIALES",Replacer.ReplaceText,{"FACULTAD / INSTITUTO"}),
				    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2","FACULTAD JURISPRUDENCIA Y CIENCIAS POLITICAS Y SOCIALES","FACULTAD DE JURISPRUDENCIA Y CIENCIAS POLITICAS Y SOCIALES",Replacer.ReplaceText,{"FACULTAD / INSTITUTO"}),
				    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3","FACULTAD JURISPRUDENCIA Y CIENCIAS POLÍTICAS Y SOCIALES","FACULTAD DE JURISPRUDENCIA Y CIENCIAS POLITICAS Y SOCIALES",Replacer.ReplaceText,{"FACULTAD / INSTITUTO"}),
				    #"Filas filtradas2" = Table.SelectRows(#"Valor reemplazado4", each true),
				    #"Valor reemplazado5" = Table.ReplaceValue(#"Filas filtradas2","UNIDAD ACADÉMICA DE FORMACIÓN TÉCNICA Y TECNOLÓGICA SALVADOR ALLENDE","UCUENCA TEC",Replacer.ReplaceText,{"FACULTAD / INSTITUTO"}),
				    #"Personalizada agregada1" = Table.AddColumn(#"Valor reemplazado5", "FACULTAD_KEY", each Text.Upper(
				    Text.Trim(
				        Text.Replace(
				        Text.Replace(
				        Text.Replace(
				        Text.Replace(
				        Text.Replace(
				        Text.Replace([#"FACULTAD / INSTITUTO"],
				        "Á","A"),
				        "É","E"),
				        "Í","I"),
				        "Ó","O"),
				        "Ú","U"),
				        "Ñ","N")
				    )
				)),
				    #"Filas filtradas3" = Table.SelectRows(#"Personalizada agregada1", each true)
				in
				    #"Filas filtradas3"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

