table silver_catastropure
	excludeFromModelRefresh
	lineageTag: f4a8ca57-0461-4fa9-9503-2c64037042e0

	measure 'Total Investigadores' = DISTINCTCOUNT('silver_catastropure'[investigador])
		formatString: 0
		lineageTag: 66774682-34c4-4e09-9870-7aeabebc4c2d

	measure 'Total Grupos' = DISTINCTCOUNT('silver_catastropure'[grupo_investigacion])
		formatString: 0
		lineageTag: b8d1b728-e49f-4783-bc95-05b1b312c14e

	measure 'Inv Académico' = CALCULATE([Total Investigadores], silver_catastropure[Vicerrectorado]= "Vicerrectorado Académico")
		formatString: 0
		lineageTag: 97222c0d-5c21-49b7-b614-66ee18f2443b

	measure 'Inv Investigación' = CALCULATE([Total Investigadores], 'silver_catastropure'[Vicerrectorado] = "Vicerrectorado de Investigación e Innovación")
		formatString: 0
		lineageTag: ac619093-6c5f-4297-83df-716a3d573968

	measure 'Grupos Académico' = CALCULATE([Total Grupos], 'silver_catastropure'[Vicerrectorado] = "Vicerrectorado Académico")
		formatString: 0
		lineageTag: 80924336-a0da-4439-bb4e-e5e8924e5b92

	measure 'Grupos Investigación' = CALCULATE([Total Grupos], 'silver_catastropure'[Vicerrectorado] = "Vicerrectorado de Investigación e Innovación", 'silver_catastropure'[grupo_investigacion] <> "Sin grupo asignado")
		formatString: 0
		lineageTag: e6c7c57f-ed86-41da-99ce-63530f66d0fd

	measure 'Total Facultades' =
			
			CALCULATE(
			    DISTINCTCOUNT('silver_catastropure'[Unidad_Investigacion]),
			    'silver_catastropure'[Vicerrectorado] = "Vicerrectorado Académico"
			)
		formatString: 0
		lineageTag: 8e9c37a1-e130-4619-8ae6-0dd253db294e

	measure 'Total Departamentos' =
			
			CALCULATE(
			    DISTINCTCOUNT('silver_catastropure'[Unidad_Investigacion]),
			    'silver_catastropure'[Vicerrectorado] = "Vicerrectorado de Investigación e Innovación"
			)
		formatString: 0
		lineageTag: dea29e65-6ad8-4c06-a33d-845338b40a56

	measure Total_PhD = ```
			
			CALCULATE(
			    [Total Investigadores],
			    'silver_catastropure'[TIPO TÍTULO] = "DOCTOR (Ph.D)"
			)
			
			```
		formatString: 0
		lineageTag: 19ebe20d-1e67-4e9e-8dc5-83c0e8d6abc6

	measure Total_Maestria =
			
			CALCULATE(
			    [Total Investigadores],
			    'silver_catastropure'[TIPO TÍTULO] = "MAESTRÍA O EQUIVALENTE"
			)
		formatString: 0
		lineageTag: a545bf05-13be-42d3-8ccf-7f598eb8c96d

	measure Total_Especia_Salud =
			
			CALCULATE(
			    [Total Investigadores],
			    'silver_catastropure'[TIPO TÍTULO] = "ESPECIALISTA AREA SALUD"
			)
		formatString: 0
		lineageTag: 5f8b6ad2-9ea4-4b96-bc50-2d2b553cc786

	measure Pct_PhD =
			
			DIVIDE([Total_PhD], [Total Investigadores], 0)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: bb74c94d-613e-419a-ae94-2bb16f3d9098

	measure Pct_Especialidad_Salud =
			
			DIVIDE([Total_Especia_Salud], [Total Investigadores], 0)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 1811d02a-3f39-456f-9be2-f8658b035a82

	measure Pct_Maestria =
			
			DIVIDE([Total_Maestria], [Total Investigadores], 0)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 3d120090-4079-4e4c-a23f-62741c2444bc

	measure Antiguedad_Promedio =
			
			AVERAGEX(
			    'silver_catastropure',
			    DATEDIFF('silver_catastropure'[FECHA_INGRESO], TODAY(), YEAR)
			)
		lineageTag: 6fbc8557-fc50-4361-8e27-75511422e8f2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Años_Titularidad =
			
			AVERAGEX(
			    FILTER(
			        silver_catastropure,
			        NOT ISBLANK(silver_catastropure[FECHA_TITULARIDAD]) &&
			        NOT ISBLANK(silver_catastropure[FECHA_INGRESO])
			    ),
			    DATEDIFF(silver_catastropure[FECHA_INGRESO], silver_catastropure[FECHA_TITULARIDAD], YEAR)
			)
		lineageTag: a9c457c7-4237-4264-806b-84ba333c1a12

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Antiguedad_General =
			
			AVERAGEX(
			    FILTER(
			        silver_catastropure,
			        NOT ISBLANK(silver_catastropure[FECHA_INGRESO])
			    ),
			    DATEDIFF(silver_catastropure[FECHA_INGRESO], TODAY(), YEAR)
			)
		lineageTag: be532b45-fbb8-4d05-9337-5dcc3eac95df

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Inv_Principales =
			
			CALCULATE(
			    [Total Investigadores],
			    silver_catastropure[CALIDAD] = "PRINCIPAL"
			)
		formatString: 0
		lineageTag: 2836f407-28e6-4cc6-9de7-77961665cf91

	measure Pct_Principales =
			
			DIVIDE([Inv_Principales], [Total_Investigadores], 0)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: b3fdf546-b930-4fe0-9e34-329325d9c391

	measure Inv_Agregados = ```
			
			CALCULATE(
			    [Total Investigadores],
			    silver_catastropure[CALIDAD] = "AGREGADO"
			)
			
			```
		formatString: 0
		lineageTag: 397fef67-bdc8-4d6a-b27c-d1bf4829739a

	measure Pct_Agregados = ```
			
			DIVIDE([Inv_Agregados], [Total Investigadores], 0)
			
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 3f0bd62e-8363-4755-aea5-545751dfd351

	measure Inv_Auxiliares =
			
			CALCULATE(
			    [Total Investigadores],
			    silver_catastropure[CALIDAD] = "AUXILIAR"
			)
		formatString: 0
		lineageTag: 3596dc90-ade0-4301-8a65-75afe3cbed38

	measure Pct_Auxiliares =
			
			DIVIDE([Inv_Auxiliares], [Total Investigadores], 0)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: c87998c0-c286-4a76-a9fc-f4aa90798289

	column investigador
		dataType: string
		lineageTag: f1d97e8b-4202-49da-9682-58c6b6a50047
		summarizeBy: none
		sourceColumn: investigador

		annotation SummarizationSetBy = Automatic

	column facultad
		dataType: string
		lineageTag: 6446f40e-0b96-414e-bdde-51706c9c54e3
		summarizeBy: none
		sourceColumn: facultad

		annotation SummarizationSetBy = Automatic

	column departamento
		dataType: string
		lineageTag: c958ed3c-01af-46d6-9cf0-cea2eafb8641
		summarizeBy: none
		sourceColumn: departamento

		annotation SummarizationSetBy = Automatic

	column pagina
		dataType: int64
		formatString: 0
		lineageTag: 99e84604-cacb-42c1-a7ee-860e7d4c9580
		summarizeBy: sum
		sourceColumn: pagina

		annotation SummarizationSetBy = Automatic

	column url_perfil
		dataType: string
		lineageTag: 918ba208-c222-45d0-b6ef-531c25aef6bd
		summarizeBy: none
		sourceColumn: url_perfil

		annotation SummarizationSetBy = Automatic

	column fecha_extraccion
		dataType: dateTime
		formatString: General Date
		lineageTag: 10b6b9f0-fdc8-4505-8784-f89518ee0088
		summarizeBy: none
		sourceColumn: fecha_extraccion

		variation Variación
			isDefault
			relationship: 5dcb00ba-26dc-4b55-86cb-af75ed7c2c7b
			defaultHierarchy: LocalDateTable_cb049f35-0d3a-448b-90bf-ea4f0695f414.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Atributo
		dataType: string
		lineageTag: 88176434-c6f0-4a0c-acd9-ecba0c2f94f1
		summarizeBy: none
		sourceColumn: Atributo

		annotation SummarizationSetBy = Automatic

	column grupo_investigacion
		dataType: string
		lineageTag: ab6c0cb4-8180-4c21-ba8c-45d37803e50c
		summarizeBy: none
		sourceColumn: grupo_investigacion

		annotation SummarizationSetBy = Automatic

	column unidad_real
		dataType: string
		lineageTag: 6dd0ce6b-d981-45ff-b40b-48dc00fc77f0
		summarizeBy: none
		sourceColumn: unidad_real

		annotation SummarizationSetBy = Automatic

	column Vicerrectorado
		dataType: string
		lineageTag: c92e9b67-a758-445f-a72f-944a6850ba91
		summarizeBy: none
		sourceColumn: Vicerrectorado

		annotation SummarizationSetBy = Automatic

	column Unidad_Investigacion
		dataType: string
		lineageTag: d89a1b3e-c37b-4e33-b90d-0639ec22da03
		summarizeBy: none
		sourceColumn: Unidad_Investigacion

		annotation SummarizationSetBy = Automatic

	column GENERO
		dataType: string
		lineageTag: 16447a29-99a2-4618-956a-16657c739455
		summarizeBy: none
		sourceColumn: GENERO

		annotation SummarizationSetBy = Automatic

	column FECHA_NACIMIENTO
		dataType: string
		lineageTag: 3c78a5dc-c916-4fb1-abd9-0033e72f6190
		summarizeBy: none
		sourceColumn: FECHA_NACIMIENTO

		annotation SummarizationSetBy = Automatic

	column TIPO_SERVIDOR
		dataType: string
		lineageTag: c1ec1572-7f6e-4b8d-ad34-0a84e75aca78
		summarizeBy: none
		sourceColumn: TIPO_SERVIDOR

		annotation SummarizationSetBy = Automatic

	column ESTADO
		dataType: string
		lineageTag: 3ea03f36-c5b2-4bdb-9e62-4066bda7cdbd
		summarizeBy: none
		sourceColumn: ESTADO

		annotation SummarizationSetBy = Automatic

	column CARGO
		dataType: string
		lineageTag: 69e8f78e-14fd-4931-980b-1919754710f2
		summarizeBy: none
		sourceColumn: CARGO

		annotation SummarizationSetBy = Automatic

	column FECHA_INGRESO
		dataType: string
		lineageTag: 719c3ebf-0138-4d81-b88b-4e4bdccac4e0
		summarizeBy: none
		sourceColumn: FECHA_INGRESO

		annotation SummarizationSetBy = Automatic

	column FECHA_TITULARIDAD
		dataType: string
		lineageTag: 070288da-5e09-4e1b-acb2-29231b04a381
		summarizeBy: none
		sourceColumn: FECHA_TITULARIDAD

		annotation SummarizationSetBy = Automatic

	column MODALIDAD_EMPLEO
		dataType: string
		lineageTag: b847b5ec-d994-44a8-af80-e10972000624
		summarizeBy: none
		sourceColumn: MODALIDAD_EMPLEO

		annotation SummarizationSetBy = Automatic

	column CALIDAD
		dataType: string
		lineageTag: 1aeb0f9f-5fc2-4417-9de8-ec83dac3c1a2
		summarizeBy: none
		sourceColumn: CALIDAD

		annotation SummarizationSetBy = Automatic

	column DEPENDENCIA
		dataType: string
		lineageTag: e37b25db-651c-4e2d-ac28-da7b187c4f19
		summarizeBy: none
		sourceColumn: DEPENDENCIA

		annotation SummarizationSetBy = Automatic

	column 'CANTON DE RESIDENCIA'
		dataType: string
		lineageTag: 76990091-4a2e-4ae6-9705-8ca1e2058683
		summarizeBy: none
		sourceColumn: CANTON DE RESIDENCIA

		annotation SummarizationSetBy = Automatic

	column TIPO_DEDICACION_1
		dataType: string
		lineageTag: 5baf995f-7e18-4133-8042-c139c487e3ff
		summarizeBy: none
		sourceColumn: TIPO_DEDICACION_1

		annotation SummarizationSetBy = Automatic

	column TIPO_DEDICACION_2
		dataType: string
		lineageTag: 8a1f0f86-ca31-41ed-95c7-42c25d5535b6
		summarizeBy: none
		sourceColumn: TIPO_DEDICACION_2

		annotation SummarizationSetBy = Automatic

	column 'UNIDAD ACADÉMICA_1'
		dataType: string
		lineageTag: 8a21783f-4504-4e8f-b7bd-70a865906a8f
		summarizeBy: none
		sourceColumn: UNIDAD ACADÉMICA_1

		annotation SummarizationSetBy = Automatic

	column 'UNIDAD ACADÉMICA_2'
		dataType: string
		lineageTag: 837d88c0-6632-43b9-98a5-3f99e749c1c0
		summarizeBy: none
		sourceColumn: UNIDAD ACADÉMICA_2

		annotation SummarizationSetBy = Automatic

	column 'PAIS ORIGEN'
		dataType: string
		lineageTag: f17b4e4a-a165-4ab3-9b9d-4e6d9d22214e
		summarizeBy: none
		sourceColumn: PAIS ORIGEN

		annotation SummarizationSetBy = Automatic

	column TIPO_PERSONAL
		dataType: string
		lineageTag: 63d47e14-699a-4e8b-abd2-e39a4b0c477b
		summarizeBy: none
		sourceColumn: TIPO_PERSONAL

		annotation SummarizationSetBy = Automatic

	column SEXO
		dataType: string
		lineageTag: 57d8e558-a8ff-46a6-84b7-94fe7e333a60
		summarizeBy: none
		sourceColumn: SEXO

		annotation SummarizationSetBy = Automatic

	column 'AÑO OBTENCIÓN TITULO'
		dataType: int64
		formatString: 0
		lineageTag: ba2aa0ef-ba13-4f0b-8d55-603ad0e8903b
		summarizeBy: sum
		sourceColumn: AÑO OBTENCIÓN TITULO

		annotation SummarizationSetBy = Automatic

	column 'PAIS ESTUDIO'
		dataType: string
		lineageTag: f070b8fa-22a1-499f-b7ea-ead1b115578c
		summarizeBy: none
		sourceColumn: PAIS ESTUDIO

		annotation SummarizationSetBy = Automatic

	column 'NIVEL TÍTULO'
		dataType: string
		lineageTag: 13351699-6ddf-48a0-942a-d30fd728dba6
		summarizeBy: none
		sourceColumn: NIVEL TÍTULO

		annotation SummarizationSetBy = Automatic

	column 'TIPO TÍTULO'
		dataType: string
		lineageTag: 954f9156-e5df-4975-b808-d3eb01e510c7
		summarizeBy: none
		sourceColumn: TIPO TÍTULO

		annotation SummarizationSetBy = Automatic

	column 'NOMBRE TÍTULO'
		dataType: string
		lineageTag: 99a53d4a-f30a-45fc-9b4f-125d7eee379b
		summarizeBy: none
		sourceColumn: NOMBRE TÍTULO

		annotation SummarizationSetBy = Automatic

	column 'CAMPO AMPLIO (UNESCO)'
		dataType: string
		lineageTag: 8c2d96bb-25fe-40b4-a421-49dfe33130b0
		summarizeBy: none
		sourceColumn: CAMPO AMPLIO (UNESCO)

		annotation SummarizationSetBy = Automatic

	column 'CAMPO ESPECÍFICO (UNESCO)'
		dataType: string
		lineageTag: 7b0a6b4f-e27d-4cff-88a6-9dfbebaa6687
		summarizeBy: none
		sourceColumn: CAMPO ESPECÍFICO (UNESCO)

		annotation SummarizationSetBy = Automatic

	column 'CAMPO DETALLADO (UNESCO)'
		dataType: string
		lineageTag: 444cf7b7-5e36-4ce6-a93d-a5d1aecb9741
		summarizeBy: none
		sourceColumn: CAMPO DETALLADO (UNESCO)

		annotation SummarizationSetBy = Automatic

	column merge
		dataType: string
		lineageTag: 5a4009c3-cf9f-46e6-8d23-f91037f468cd
		summarizeBy: none
		sourceColumn: merge

		annotation SummarizationSetBy = Automatic

	column 'NOMBRES COMPLETOS'
		dataType: string
		lineageTag: 6b0ccd72-0591-447a-8e94-af8937cbd785
		summarizeBy: none
		sourceColumn: NOMBRES COMPLETOS

		annotation SummarizationSetBy = Automatic

	column Unidad_abreviada
		dataType: string
		lineageTag: 174b9ff3-47e7-4368-b5f8-073e4458c756
		summarizeBy: none
		sourceColumn: Unidad_abreviada

		annotation SummarizationSetBy = Automatic

	column 'CAMPO ESPECÍFICO (UNESCO)_limpio'
		dataType: string
		lineageTag: 3a4ee399-f532-4e77-aabd-d3026d0d6bb4
		summarizeBy: none
		sourceColumn: CAMPO ESPECÍFICO (UNESCO)_limpio

		annotation SummarizationSetBy = Automatic

	column Key_nombre
		dataType: string
		lineageTag: 78ba4673-9fcd-4e2a-ab94-bab02ee3cfee
		summarizeBy: none
		sourceColumn: Key_nombre

		annotation SummarizationSetBy = Automatic

	hierarchy 'Unidad_abreviada Jerarquía'
		lineageTag: a43093fc-39b4-42bf-a8e9-b9554a0a0a7b

		level Unidad_abreviada
			lineageTag: 1a58f49f-7d77-49a8-9747-f095ff92058f
			column: Unidad_abreviada

		level grupo_investigacion
			lineageTag: 25caa3cd-9368-456c-8522-ad946b272de1
			column: grupo_investigacion

	partition silver_catastropure = m
		mode: import
		source =
				let
				    Origen = Table.NestedJoin(silver_investigadores, {"merge"}, silver_jerarquía, {"grupo_merge_jerarquia"}, "silver_jerarquía", JoinKind.Inner),
				    #"Se expandió silver_jerarquía" = Table.ExpandTableColumn(Origen, "silver_jerarquía", {"Vicerrectorado", "Unidad_Investigacion"}, {"Vicerrectorado", "Unidad_Investigacion"}),
				    #"Texto limpio" = Table.TransformColumns(#"Se expandió silver_jerarquía",{{"investigador", Text.Clean, type text}}),
				    #"Texto recortado" = Table.TransformColumns(#"Texto limpio",{{"investigador", Text.Trim, type text}}),
				    #"Texto en mayúsculas" = Table.TransformColumns(#"Texto recortado",{{"investigador", Text.Upper, type text}}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Texto en mayúsculas", {"investigador"}, catastro_docentes, {"investigador"}, "catastro_docentes", JoinKind.LeftOuter),
				    #"Se expandió catastro_docentes" = Table.ExpandTableColumn(#"Consultas combinadas", "catastro_docentes", {"GENERO", "FECHA_NACIMIENTO", "TIPO_SERVIDOR", "ESTADO", "CARGO", "FECHA_INGRESO", "FECHA_TITULARIDAD", "MODALIDAD_EMPLEO", "CALIDAD", "DEPENDENCIA", "CANTON DE RESIDENCIA", "TIPO_DEDICACION_1", "TIPO_DEDICACION_2", "UNIDAD ACADÉMICA_1", "UNIDAD ACADÉMICA_2", "NOMBRES COMPLETOS", "PAIS ORIGEN", "TIPO_PERSONAL", "SEXO", "AÑO OBTENCIÓN TITULO", "PAIS ESTUDIO", "NIVEL TÍTULO", "TIPO TÍTULO", "NOMBRE TÍTULO", "CAMPO AMPLIO (UNESCO)", "CAMPO ESPECÍFICO (UNESCO)", "CAMPO DETALLADO (UNESCO)"}, {"GENERO", "FECHA_NACIMIENTO", "TIPO_SERVIDOR", "ESTADO", "CARGO", "FECHA_INGRESO", "FECHA_TITULARIDAD", "MODALIDAD_EMPLEO", "CALIDAD", "DEPENDENCIA", "CANTON DE RESIDENCIA", "TIPO_DEDICACION_1", "TIPO_DEDICACION_2", "UNIDAD ACADÉMICA_1", "UNIDAD ACADÉMICA_2", "NOMBRES COMPLETOS", "PAIS ORIGEN", "TIPO_PERSONAL", "SEXO", "AÑO OBTENCIÓN TITULO", "PAIS ESTUDIO", "NIVEL TÍTULO", "TIPO TÍTULO", "NOMBRE TÍTULO", "CAMPO AMPLIO (UNESCO)", "CAMPO ESPECÍFICO (UNESCO)", "CAMPO DETALLADO (UNESCO)"}),
				    #"Personalizada agregada" = Table.AddColumn(#"Se expandió catastro_docentes", "Unidad_abreviada", each Text.Replace(
				    Text.Replace(
				        Text.Replace([Unidad_Investigacion], "Facultad de ", ""),
				    "Departamento de ", ""),
				"Departamento Interdisciplinario de ", "")),
				    #"Filas filtradas" = Table.SelectRows(#"Personalizada agregada", each true),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Filas filtradas",{{"AÑO OBTENCIÓN TITULO", Int64.Type}}),
				    #"Personalizada agregada1" = Table.AddColumn(#"Tipo cambiado", "CAMPO ESPECÍFICO (UNESCO)_limpio", each let
				    texto = Text.Upper([#"CAMPO ESPECÍFICO (UNESCO)"]),
				    palabras = Text.Split(texto, " "),
				    stopwords = {"DE", "LA", "EL", "LOS", "LAS", "DEL", "EN", "Y", "E", "O", "A", "AL", "CON", "POR", "PARA", "SU", "SE", "UN", "UNA", "UNOS", "UNAS", "LO", "LE", "ES", "AFINES","NO", "SI", "COMO", "MÁS", "PERO", "ENTRE", "HASTA", "DESDE", "SOBRE", "TODO", "OTRO", "OTRA", "OTROS", "OTRAS", "ESTE", "ESTA", "ESTOS", "ESTAS", "ESE", "ESA", "ESOS", "ESAS", "AQUEL", "AQUELLA", "AQUELLOS", "AQUELLAS"},
				    filtradas = List.Select(palabras, each not List.Contains(stopwords, _)),
				    resultado = Text.Combine(filtradas, " ")
				in
				    resultado),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Personalizada agregada1","REINO UNIDO (INGLATERRA)","REINO UNIDO",Replacer.ReplaceText,{"PAIS ESTUDIO"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","ESTADOS UNIDOS","USA",Replacer.ReplaceText,{"PAIS ESTUDIO"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","USA","U.S.A",Replacer.ReplaceText,{"PAIS ESTUDIO"}),
				    #"Personalizada agregada2" = Table.AddColumn(#"Valor reemplazado2", "Key_nombre", each Text.Upper(
				    Text.Replace(
				        Text.Replace(
				            Text.Replace(
				                Text.Replace(
				                    Text.Replace(
				                        Text.Replace(
				                            Text.Replace(
				                                Text.Replace(
				                                    Text.Replace(
				                                        Text.Trim(Text.Clean([investigador])),
				                                        "Á", "A"
				                                    ),
				                                    "É", "E"
				                                ),
				                                "Í", "I"
				                            ),
				                            "Ó", "O"
				                        ),
				                        "Ú", "U"
				                    ),
				                    "Ü", "U"
				                ),
				                "Ñ", "N"
				            ),
				            ",", ""
				        ),
				        "  ", " "
				    )
				))
				in
				    #"Personalizada agregada2"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

