table silver_jerarquía
	lineageTag: 060ebf7a-1e0b-4d28-bc3f-a3683ea1dc5c

	column Vicerrectorado
		dataType: string
		lineageTag: f4e06bbe-d21d-45cf-abfc-8015ebe4d1e5
		summarizeBy: none
		sourceColumn: Vicerrectorado

		annotation SummarizationSetBy = Automatic

	column Unidad_Investigacion
		dataType: string
		lineageTag: dd128418-a954-4d6a-99b4-05ad55c7863f
		summarizeBy: none
		sourceColumn: Unidad_Investigacion

		annotation SummarizationSetBy = Automatic

	column Grupo_Investigacion
		dataType: string
		lineageTag: f428fd5b-e570-4339-8efd-c02b583aab4b
		summarizeBy: none
		sourceColumn: Grupo_Investigacion

		annotation SummarizationSetBy = Automatic

	column grupo_merge_jerarquia
		dataType: string
		lineageTag: 00a281f3-a37a-4877-bffe-880158e9c9bb
		summarizeBy: none
		sourceColumn: grupo_merge_jerarquia

		annotation SummarizationSetBy = Automatic

	partition silver_jerarquía = m
		mode: import
		source = ```
				let
				    // Crear la tabla de jerarquía manualmente
				    Origen = #table(
				        {"Vicerrectorado", "Unidad_Investigacion", "Grupo_Investigacion"},
				        {
				        // ============ VICERRECTORADO ACADÉMICO ============
				        {"Vicerrectorado Académico", "Facultad de Arquitectura y Urbanismo", "Ciudad, Territorio y Movilidad (CITMOV)"},
				        {"Vicerrectorado Académico", "Facultad de Arquitectura y Urbanismo", "Ciudad Patrimonio Mundial"},
				        {"Vicerrectorado Académico", "Facultad de Arquitectura y Urbanismo", "Entorno Construido Sostenible (ECOS)"},
				        {"Vicerrectorado Académico", "Facultad de Arquitectura y Urbanismo", "Laboratorio de Dinámicas Urbano-Territoriales Contemporáneas (LDUT)"},
				        {"Vicerrectorado Académico", "Facultad de Arquitectura y Urbanismo", "PROYEKTA"},
				        {"Vicerrectorado Académico", "Facultad de Arquitectura y Urbanismo", "Territorium"},
				        {"Vicerrectorado Académico", "Facultad de Arquitectura y Urbanismo", "VirtualTech"},
				        {"Vicerrectorado Académico", "Facultad de Arquitectura y Urbanismo", "Vulnerabilidad Sísmica del patrimonio edificado de Cuenca"},
				        {"Vicerrectorado Académico", "Facultad de Artes", "MediaLab: Arte, Diseño y Tecnología"},
				        {"Vicerrectorado Académico", "Facultad de Artes", "Metodologías, Procesos y Prácticas Artísticas"},
				        {"Vicerrectorado Académico", "Facultad de Artes", "Nueva ensayística sobre las artes y el diseño en el tercer milenio"},
				        {"Vicerrectorado Académico", "Facultad de Artes", "Pedagogía de las Artes"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias Agropecuarias", "Biotecnología agropecuaria"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias Agropecuarias", "Biotecnología de la Reproducción Animal"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias Agropecuarias", "Ecología Forestal, Agroecosistemas y Silvopasturas en Sistemas Ganaderos."},
				        {"Vicerrectorado Académico", "Facultad de Ciencias Agropecuarias", "GeoinfoRmática, Agrociencias y Soluciones Sostenibles (G.R.A.S.S)"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias Agropecuarias", "Producción Animal"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias Agropecuarias", "Sanidad animal y salud pública"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias Agropecuarias", "Suelos y producción"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias de la Hospitalidad", "Desarrollo local a través del turismo (PREIT-TOUR)"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias de la Hospitalidad", "Indicadores Turísticos"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias de la Hospitalidad", "Turismo, Sostenibilidad y Patrimonio (TUR-Ecuador)"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias Médicas", "Atención Primaria de Salud (GIAPS)"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias Médicas", "Gestión del Cuidado"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias Médicas", "Inmuno-reumatología"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias Médicas", "Neurodesarrollo"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias Médicas", "Pharmacology and Nutritional Sciences (PharmaNut)"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias Médicas", "Salud Integral del/la Adolescente"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias Médicas", "Salud Intercultural"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias Médicas", "Salud Mental"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias Médicas", "Salud pública, alimentación y actividad física en el ciclo de la vida"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias Médicas", "Salud Sexual y Reproductiva"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias Químicas", "Ecología Acuática"},
				        {"Vicerrectorado Académico", "Facultad de Filosofía, Letras y Ciencias de la Educación", "Cine, Periodismo y Comunicación (CIPEC)"},
				        {"Vicerrectorado Académico", "Facultad de Filosofía, Letras y Ciencias de la Educación", "Educación Física, Deporte y Salud (EDFIDYS)"},
				        {"Vicerrectorado Académico", "Facultad de Filosofía, Letras y Ciencias de la Educación", "Estudios Interculturales (GEI)"},
				        {"Vicerrectorado Académico", "Facultad de Filosofía, Letras y Ciencias de la Educación", "Filosofía Política y Derecho"},
				        {"Vicerrectorado Académico", "Facultad de Filosofía, Letras y Ciencias de la Educación", "Formación e Innovación Docente (GIFID)"},
				        {"Vicerrectorado Académico", "Facultad de Filosofía, Letras y Ciencias de la Educación", "Historia de Cuenca y su Región"},
				        {"Vicerrectorado Académico", "Facultad de Filosofía, Letras y Ciencias de la Educación", "Investigaciones Cinematográficas - GIC"},
				        {"Vicerrectorado Académico", "Facultad de Filosofía, Letras y Ciencias de la Educación", "Lenguaje, culturas y representaciones"},
				        {"Vicerrectorado Académico", "Facultad de Filosofía, Letras y Ciencias de la Educación", "Literaturas Regionales"},
				        {"Vicerrectorado Académico", "Facultad de Filosofía, Letras y Ciencias de la Educación", "Migración Internacional, Derechos y Políticas"},
				        {"Vicerrectorado Académico", "Facultad de Ingeniería", "Monitorización de Salud Estructural"},
				        {"Vicerrectorado Académico", "Facultad de Ingeniería", "Tecnologías aplicadas en Salud"},
				        {"Vicerrectorado Académico", "Facultad de Jurisprudencia y Ciencias Políticas y Sociales", "Feminismo, Derechos humanos y Tecnología"},
				        {"Vicerrectorado Académico", "Facultad de Odontología", "Biomateriales y Tecnologías Dentales Aplicadas"},
				        {"Vicerrectorado Académico", "Facultad de Odontología", "Crecimiento, desarrollo y biología Craneofacial"},
				        {"Vicerrectorado Académico", "Facultad de Odontología", "Odontología Digital y Materiales CAD/CAM"},
				        {"Vicerrectorado Académico", "Facultad de Odontología", "Periodoncia e implantología oral (GIPIO)"},
				        {"Vicerrectorado Académico", "Facultad de Odontología", "Rehabilitación Oral (GIRO)"},
				        {"Vicerrectorado Académico", "Facultad de Psicología", "Inteligencia Emocional"},
				        {"Vicerrectorado Académico", "Facultad de Psicología", "Procesos Psicológicos Básicos"},
				        {"Vicerrectorado Académico", "Facultad de Psicología", "Psicología Clínica y de la Salud"},
				        
				        // ============ VICERRECTORADO DE INVESTIGACIÓN E INNOVACIÓN ============
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Biociencias", "Alimentación, Nutrición, Salud y Actividad Física"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Biociencias", "Ingeniería de las Reacciones Químicas, Catálisis y Tecnologías del Medio Ambiente (IRCMA)"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Biociencias", "Plantas Medicinales y Productos Naturales"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Biociencias", "Terapéutica y Toxicología Clínica"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Ciencias de la Computación", "Gestión del Conocimiento"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Ciencias de la Computación", "GSigma – Grupo de Sistemas Inteligentes para la Gestión, Modelado y Aprendizaje"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Ciencias de la Computación", "Infraestructura de Datos Espaciales y Ciudades Inteligentes"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Ciencias de la Computación", "Ingeniería de Software"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Ciencias de la Computación", "Innovación Tecnológica (GIIT)"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Ciencias de la Computación", "Models, Analysis and Simulations Applied to Transport Systems (MAS)"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Economía, Empresa y Desarrollo Sostenible", "Acompañamiento Organizaciónal al Desarrollo (ACORDES)"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Economía, Empresa y Desarrollo Sostenible", "Contabilidad, Finanzas y Tributación (GiCOFT)"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Economía, Empresa y Desarrollo Sostenible", "Economía Regional"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Economía, Empresa y Desarrollo Sostenible", "Empresarial"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Economía, Empresa y Desarrollo Sostenible", "Estudios Interdisciplinarios de Género"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Economía, Empresa y Desarrollo Sostenible", "Estudios Sociales de Ciencia y Tecnología"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Economía, Empresa y Desarrollo Sostenible", "Gestión Estratégica y de Negocios"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Economía, Empresa y Desarrollo Sostenible", "Macroeconomía y Desarrollo (GIMADE)"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Economía, Empresa y Desarrollo Sostenible", "Water Law and Management"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Educación", "Educación Matemática"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Educación", "EFL Teacher Education"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Educación", "English Learning and Acquisition (ELA)"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Educación", "GITEICU – Grupo de Investigación en Tecnología Educativa, Innovación, y Conocimiento en el contexto Universitario."},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Educación", "Políticas Educativas"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Educación", "Sexualidad, género y educación sexual (HUMSEX)"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Educación", "Sistema Familiar"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Educación", "Trayectorias académicas e indicadores educativos"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Ingeniería Civil", "Estructuras, sismicidad y materiales (ES&M)"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Ingeniería Civil", "Geotecnia vialidad y trasportación (GV&T)"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Ingeniería Civil", "Ingeniería del Agua y Saneamiento Ambiental (IA&SA)"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Ingeniería Civil", "Manejo del Agua y del Suelo (PROMAS)"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Ingeniería Civil", "Red Sísmica del Austro"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Ingeniería Eléctrica, Electrónica y Telecomunicaciones", "Electrónica y Control"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Ingeniería Eléctrica, Electrónica y Telecomunicaciones", "Procesamiento Digital de Señales y Comunicaciones"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Ingeniería Eléctrica, Electrónica y Telecomunicaciones", "Sistemas de Energía Eléctrica"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Química Aplicada y Sistemas de Producción", "Biotecnología y Biodiversidad"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Química Aplicada y Sistemas de Producción", "Calidad del aire y Toxicología medioambiental (CATOx-CEA)"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Química Aplicada y Sistemas de Producción", "Energía, Biomasa y Bioenergía"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Química Aplicada y Sistemas de Producción", "Evaluación de Riesgos Ambientales en Sistemas de Producción y Servicios (RISKEN)"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Química Aplicada y Sistemas de Producción", "Industrial Management and Innovation Research (IMAGINE)"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Química Aplicada y Sistemas de Producción", "Ingeniería Industrial e Innovación (GI3)"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Química Aplicada y Sistemas de Producción", "Nanotecnología Aplicada a Medio Ambiente (N@NO-CEA)"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Química Aplicada y Sistemas de Producción", "Tecnologías Sostenibles en Calidad y Remediación Ambiental en Agua (TECNOCEA – H2O)"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Recursos Hídricos y Ciencias Ambientales", "Agroforestería y manejo del paisaje"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Recursos Hídricos y Ciencias Ambientales", "Hidrología y Clima"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Recursos Hídricos y Ciencias Ambientales", "Saneamiento Ambiental"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento Interdisciplinario de Espacio y Población", "Ciudades Sustentables (LlactaLAB)"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento Interdisciplinario de Espacio y Población", "Economía Circular Inclusiva y Desarrollo Sostenible"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento Interdisciplinario de Espacio y Población", "Etnografía Interdisciplinaria (KALEIDOS)"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento Interdisciplinario de Espacio y Población", "Población y Desarrollo Local Sustentable (PYDLOS)"},
				        
				        
				
				            // ============ REGISTROS PARA INVESTIGADORES SIN GRUPO ============
				
				        // Vicerrectorado Académico - Facultades sin grupo
				        {"Vicerrectorado Académico", "Facultad de Arquitectura y Urbanismo", "Sin grupo asignado"},
				        {"Vicerrectorado Académico", "Facultad de Artes", "Sin grupo asignado"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias Agropecuarias", "Sin grupo asignado"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias de la Hospitalidad", "Sin grupo asignado"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias Médicas", "Sin grupo asignado"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias Químicas", "Sin grupo asignado"},
				        {"Vicerrectorado Académico", "Facultad de Filosofía, Letras y Ciencias de la Educación", "Sin grupo asignado"},
				        {"Vicerrectorado Académico", "Facultad de Ingeniería", "Sin grupo asignado"},
				        {"Vicerrectorado Académico", "Facultad de Jurisprudencia y Ciencias Políticas y Sociales", "Sin grupo asignado"},
				        {"Vicerrectorado Académico", "Facultad de Odontología", "Sin grupo asignado"},
				        {"Vicerrectorado Académico", "Facultad de Psicología", "Sin grupo asignado"},
				        {"Vicerrectorado Académico", "Facultad de Ciencias Económicas y Administrativas", "Sin grupo asignado"},
				
				        // Vicerrectorado de Investigación e Innovación - Departamentos sin grupo
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Biociencias", "Sin grupo asignado"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Ciencias de la Computación", "Sin grupo asignado"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Economía, Empresa y Desarrollo Sostenible", "Sin grupo asignado"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Educación", "Sin grupo asignado"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Ingeniería Civil", "Sin grupo asignado"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Ingeniería Eléctrica, Electrónica y Telecomunicaciones", "Sin grupo asignado"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Química Aplicada y Sistemas de Producción", "Sin grupo asignado"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento de Recursos Hídricos y Ciencias Ambientales", "Sin grupo asignado"},
				        {"Vicerrectorado de Investigación e Innovación", "Departamento Interdisciplinario de Espacio y Población", "Sin grupo asignado"}
				        }
				
				            ),
				    #"Personalizada agregada" = Table.AddColumn(Origen, "grupo_merge_jerarquia", each if [Grupo_Investigacion] = "Sin grupo asignado" then 
				        "Sin grupo asignado|" & [Unidad_Investigacion]
				    else 
				        [Grupo_Investigacion])
				in
				    #"Personalizada agregada"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

