table silver_investigadores
	lineageTag: 9f848272-b5e7-4a32-ae88-d160eb06ee1d

	measure Total_Investigadores =
			
			DISTINCTCOUNT('silver_investigadores'[investigador])
		formatString: 0
		lineageTag: ae6dc0ac-1c1b-4d07-a33c-228fe56d194f

	column investigador
		dataType: string
		lineageTag: dc94d11c-5c1b-444d-9eaa-7472dfef2071
		summarizeBy: none
		sourceColumn: investigador

		annotation SummarizationSetBy = Automatic

	column facultad
		dataType: string
		lineageTag: 7ebed33d-994f-499f-842a-5840aea0e4a6
		summarizeBy: none
		sourceColumn: facultad

		annotation SummarizationSetBy = Automatic

	column departamento
		dataType: string
		lineageTag: 3dec0336-c6ef-442b-9c5b-071284cfb886
		summarizeBy: none
		sourceColumn: departamento

		annotation SummarizationSetBy = Automatic

	column pagina
		dataType: int64
		formatString: 0
		lineageTag: dcdfa534-42b3-498e-bb7d-2c1ec40a38b9
		summarizeBy: sum
		sourceColumn: pagina

		annotation SummarizationSetBy = Automatic

	column url_perfil
		dataType: string
		lineageTag: 1762075c-d029-4372-ad5f-689689c06d9d
		summarizeBy: none
		sourceColumn: url_perfil

		annotation SummarizationSetBy = Automatic

	column fecha_extraccion
		dataType: dateTime
		formatString: General Date
		lineageTag: b3f2e5a5-aa48-464d-9387-bb766cf6cd8a
		summarizeBy: none
		sourceColumn: fecha_extraccion

		variation Variación
			isDefault
			relationship: ca98a42a-38cf-40f1-928f-1824cc90d272
			defaultHierarchy: LocalDateTable_9a2da4ad-c70d-4fef-a2f7-430326d22bd6.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Atributo
		dataType: string
		lineageTag: cfcdf21d-df86-4077-8343-63a196bfcaa1
		summarizeBy: none
		sourceColumn: Atributo

		annotation SummarizationSetBy = Automatic

	column grupo_investigacion
		dataType: string
		lineageTag: c11ef5f5-25a3-4adc-aa72-3c9863243ba1
		summarizeBy: none
		sourceColumn: grupo_investigacion

		annotation SummarizationSetBy = Automatic

	column unidad_real
		dataType: string
		lineageTag: 43a0620a-1763-4020-9d3a-ca06570bcabb
		summarizeBy: none
		sourceColumn: unidad_real

		annotation SummarizationSetBy = Automatic

	column merge
		dataType: string
		lineageTag: dc8226cc-684e-437e-9d5a-2e168ab0cee8
		summarizeBy: none
		sourceColumn: merge

		annotation SummarizationSetBy = Automatic

	partition silver_investigadores = m
		mode: import
		source = ```
				let
				  Origen = Excel.Workbook(File.Contents("C:\Users\michu\mis-proyectos\ucuenca-sabe\data\bronze\investigacion\investigadores_raw.xlsx"), null, true),
				  #"Navegación 1" = Origen{[Item = "Sheet1", Kind = "Sheet"]}[Data],
				  #"Encabezados promovidos" = Table.PromoteHeaders(#"Navegación 1", [PromoteAllScalars = true]),
				  #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"investigador", type text}, {"facultad", type text}, {"departamento", type text}, {"grupos_investigacion", type text}, {"pagina", Int64.Type}, {"url_perfil", type text}, {"fecha_extraccion", type datetime}}, "es"),
				    #"Filas filtradas" = Table.SelectRows(#"Tipo de columna cambiado", each true),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Filas filtradas",null,"Sin grupo asignado",Replacer.ReplaceValue,{"grupos_investigacion"}),
				    #"Dividir columna por delimitador" = Table.SplitColumn(#"Valor reemplazado", "grupos_investigacion", Splitter.SplitTextByDelimiter(" | ", QuoteStyle.Csv), {"grupos_investigacion.1", "grupos_investigacion.2", "grupos_investigacion.3"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Dividir columna por delimitador",{{"grupos_investigacion.1", type text}, {"grupos_investigacion.2", type text}, {"grupos_investigacion.3", type text}}),
				    #"Columna de anulación de dinamización" = Table.UnpivotOtherColumns(#"Tipo cambiado", {"investigador", "facultad", "departamento", "pagina", "url_perfil", "fecha_extraccion"}, "Atributo", "Valor"),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columna de anulación de dinamización",{{"Valor", "grupo_investigacion"}}),
				    #"Personalizada agregada" = Table.AddColumn(#"Columnas con nombre cambiado", "unidad_real", each if [grupo_investigacion] = "Sin grupo asignado" then
				        if [facultad] <> null and [facultad] <> "" then 
				            [facultad]
				        else if [departamento] <> null and [departamento] <> "" then 
				            [departamento]
				        else 
				            "Sin clasificar"
				    else 
				        null),
				    #"Personalizada agregada1" = Table.AddColumn(#"Personalizada agregada", "merge", each if [grupo_investigacion] = "Sin grupo asignado" then 
				        "Sin grupo asignado|" & [unidad_real]
				    else 
				        [grupo_investigacion]),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Personalizada agregada1",", PhD","",Replacer.ReplaceText,{"investigador"}),
				    #"Filas filtradas1" = Table.SelectRows(#"Valor reemplazado1", each true)
				in
				    #"Filas filtradas1"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

